export const SESSION_ACTION_KEY = "SESSION_ACTION_KEY";
export const POST_USER_DETAILS = "POST_USER_DETAILS";
export const  POST_DEPOSIT_DETAILS = "POST_DEPOSIT_DETAILS";
export const GET_USER_DETAILS = "GET_USER_DETAILS";